라이브러리

In [2]:
import numpy as np

1. 다차원 배열 (Numpy)
    - Numpy는 고차원 배열(벡터, 행렬, 텐서 등)을 쉽게 다룰 수 있도록 해준다.

-  1차원 배열

In [ ]:
A = np.array([1, 2, 3, 4])

print(A)          # [1 2 3 4]
print(np.ndim(A)) # 1 (차원 수)
print(A.shape)    # (4,) (형상: 1차원, 길이 4)


[1 2 3 4]
1
(4,)


    - ndim : 배열의 차원 수
    - shape : 배열의 형태

- 2차원 배열

In [3]:
B = np.array([[1, 2], [3, 4], [5, 6]])

print(B)
# [[1 2]
#  [3 4]
#  [5 6]]

print(np.ndim(B))  # 2 (2차원 배열)
print(B.shape)     # (3, 2) (3행 2열)


[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


    - 2차원 배열은 흔히 행렬(matrix) 이라고 부른다.



2. 행렬의 내적 (dot product)
    - 행렬의 내적은 두 배열 간의 곱을 의미한다.(스칼라 곱, 행렬 곱과도 부른다.)

- 기본 행렬 곱

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


    - 계산 과정
        - 첫 번째 행×첫 번째 열=1×5+2×7=19
        - 첫 번째 행×두 번째 열=1×6+2×8=22

- (2,3) × (3,2) 행렬 곱

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
B = np.array([[1, 2], [3, 4], [5, 6]])  # (3, 2)

print(np.dot(A, B))


[[22 28]
 [49 64]]


    - (2,3) 과 (3,2) 을 곱하면 결과는 (2,2) 행렬이 된다.
    - 앞쪽 행렬의 열 수와 뒤쪽 행렬의 행 수가 일치해야 곱할 수 있다.

- 1차원 벡터와 2차원 행렬 곱

In [7]:
X = np.array([1, 2])  # (2,)
W = np.array([[1, 3, 5], [2, 4, 6]])  # (2, 3)

Y = np.dot(X, W)

print(Y)

[ 5 11 17]


    - 계산과정
- $Y_0=1×1+2×2=5$
- $Y_1=1×3+2×4=11$
- $Y_2=1×5+2×6=17$